# Generated by Django 5.2 on 2025-04-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_serviceinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImapConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('encryption', models.CharField(choices=[('None', 'None'), ('STARTTLS', 'STARTTLS'), ('SSL/TLS', 'SSL/TLS')], default='SSL/TLS', max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('poll_frequency', models.IntegerField(default=5)),
                ('imap_inbox', models.CharField(default='INBOX', max_length=255)),
                ('imap_processed_folder', models.CharField(default='INBOX/Processed', max_length=255)),
                ('imap_rejected_folder', models.CharField(default='INBOX/Rejected', max_length=255)),
                ('service_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.serviceinstance')),
            ],
        ),
    ]
