# Generated by Django 5.2 on 2025-04-13 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainGullStandardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raingull_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('processing_status', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('sending', 'Sending'), ('distributed', 'Distributed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('origin_service_id', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('signal', 'Signal'), ('whatsapp', 'WhatsApp'), ('slack', 'Slack'), ('teams', 'Teams'), ('other', 'Other')], default='other', max_length=20)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_sender', models.CharField(max_length=255)),
                ('original_sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_recipient_list', models.JSONField(blank=True, null=True)),
                ('member_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet', models.CharField(blank=True, max_length=255, null=True)),
                ('message_body', models.TextField()),
                ('additional_headers', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rg_standard_messages',
            },
        ),
    ]
