# Generated by Django 5.2 on 2025-04-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('activation_url', models.URLField(help_text='URL for the activation link. Use {token} as a placeholder for the activation token.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serviceinstance')),
            ],
        ),
    ]
