# Generated by Django 5.2 on 2025-04-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raingulluser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='raingull_user_set', related_query_name='raingull_user', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='raingulluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='raingull_user_set', related_query_name='raingull_user', to='auth.permission'),
        ),
    ]
