# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_raingulluser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raingulluser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='raingulluser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ] 