# Generated by Django 5.2 on 2025-04-20 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invitationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('admin_notification', 'Admin Notification'), ('system_error', 'System Error')], max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_systemmessagetemplate',
            },
        ),
        migrations.CreateModel(
            name='ServiceMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('invitation', 'Invitation'), ('error', 'Error'), ('notification', 'Notification')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('activation_url', models.URLField(blank=True, help_text='URL for the activation link. Use {token} as a placeholder for the activation token.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serviceinstance')),
            ],
            options={
                'db_table': 'core_servicemessagetemplate',
                'unique_together': {('service_instance', 'message_type')},
            },
        ),
        migrations.DeleteModel(
            name='InvitationMessage',
        ),
    ]
