# Generated by Django 5.2 on 2025-04-19 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_outgoingmessagequeue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('imap_poll', 'IMAP Poll'), ('message_process', 'Message Processing'), ('outgoing_send', 'Outgoing Message Send'), ('error', 'Error'), ('system', 'System Event')], max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceinstance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_auditl_event_t_f36ba9_idx'), models.Index(fields=['service_instance', 'created_at'], name='core_auditl_service_b421b5_idx')],
            },
        ),
    ]
