# Generated by Django 5.2 on 2025-04-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='raingulluser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
