# Generated by Django 5.2 on 2025-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemmessagetemplate_servicemessagetemplate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raingulluser',
            options={},
        ),
        migrations.RemoveField(
            model_name='raingulluser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='raingulluser',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='raingulluser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='raingulluser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='raingulluser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='raingulluser',
            name='web_login_enabled',
            field=models.BooleanField(default=False, help_text='Whether the user can log into the web interface'),
        ),
        migrations.AlterField(
            model_name='raingulluser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='raingulluser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='raingulluser',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='raingulluser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterModelTable(
            name='raingulluser',
            table='core_raingulluser',
        ),
    ]
