# Generated by Django 5.2 on 2025-04-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_event_t_f36ba9_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_service_b421b5_idx',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='message',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], default='success', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(default='success'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='service_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceinstance'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['service_instance'], name='core_auditl_service_c878d5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='core_auditl_event_t_04b2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status'], name='core_auditl_status_4118d1_idx'),
        ),
    ]
