# Generated by Django 5.2 on 2025-04-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_enabled_plugin_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='serviceinstance',
            old_name='active',
            new_name='enabled',
        ),
    ]
