# Generated by Django 5.2 on 2025-04-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cleanup_enabled_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='description',
        ),
        migrations.AddField(
            model_name='plugin',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
