# Generated by Django 5.2 on 2025-04-14 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_serviceinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('encryption', models.CharField(choices=[('None', 'None'), ('STARTTLS', 'STARTTLS'), ('SSL/TLS', 'SSL/TLS')], default='STARTTLS', max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('service_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.serviceinstance')),
            ],
        ),
    ]
